### ISSUE TITLE
Console wrong stats about bucket

### ISSUE THREAD

**Issue by ginn13** [minio/console#1273]
Console shows zero objects in bucket, though it is plenty of
![image](https://user-images.githubusercontent.com/11777877/144219752-709afde8-42df-4e3f-ad75-9b65584de5ab.png)
![image](https://user-images.githubusercontent.com/11777877/144220065-fed6930e-fbff-4f77-b98b-7f3ccb6f5a31.png)
If i use mc client, I can see a lot of objects
![image](https://user-images.githubusercontent.com/11777877/144220292-a360d1ea-84a4-44c4-8c93-be905b8b25e5.png)

Files were uploaded with minio python library version 7.1.2 by simple script like that
```
from minio import Minio
import urllib3

BUCKET_NAME = 'test'
FILE = 'photo.jpeg'
REPEAT_COUNT = 1000
THREADS = 16
MINIO_HOST = "minio:443"
MINIO_ACCESS_KEY = "SOME_ACCESS_KEY"
MINIO_SECRET_KEY = "SOME_SECRET_KEY"

# Create client with access and secret key.
httpClient = urllib3.PoolManager(cert_reqs='CERT_NONE',assert_hostname=False)
client = Minio(MINIO_HOST, MINIO_ACCESS_KEY, MINIO_SECRET_KEY,secure=True,http_client=httpClient)

#client.make_bucket("test")
client.fput_object(BUCKET_NAME,"photo.jpg",FILE)
```

Minio deployed with operator, here is Tenant CR

```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant-1
  namespace: minio-tenant
status:
  availableReplicas: 6
  certificates:
    autoCertEnabled: true
  currentState: Initialized
  drivesOnline: 24
  healthStatus: green
  pools:
    - legacySecurityContext: false
      ssName: minio-tenant-1-ss-0
      state: PoolInitialized
  provisionedUsers: true
  revision: 0
  syncVersion: v4.3.0
  usage:
    capacity: 117281240317952
    rawCapacity: 175921860444144
    rawUsage: 2473330720768
    usage: 9462
  writeQuorum: 8
spec:
  certConfig: {}
  credsSecret:
    name: minio-tenant-1-creds-secret
  image: minio/minio:RELEASE.2021-11-09T03-21-45Z
  imagePullSecret: {}
  mountPath: /export
  pools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - minio-tenant-1
              topologyKey: kubernetes.io/hostname
      resources: {}
      servers: 6
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/minio
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '7330077518506'
          storageClassName: direct-csi-min-io
        status: {}
      volumesPerServer: 4
  requestAutoCert: true
  users:
    - name: minio-tenant-1-user-1
scheduler:
  name: ''
```
