### ISSUE TITLE
Cluster domain from operator is not being used to proxy requests

### ISSUE THREAD

**Issue by vincentbaeten** [minio/console#1395]
The cluster domain setting from the operator has no effect and gets defaulted to "cluster.local" when I try to manage a tenant from the operator ui. 

I found that [operatorapi/proxy.go#L95](https://github.com/minio/console/blob/bbe87ecd599319f5575cd1aae021685d444d076a/operatorapi/proxy.go#L95) calls function `GetClusterDomain()`. I've tried setting the environment variable `clusterDomain` that is used by [v2.GetClusterDomain()](https://github.com/minio/operator/blob/049906f88ad0e81c4d42c7407ca2ad7f5bad9915/pkg/apis/minio.min.io/v2/helper.go#L930) manually in the deployment.yaml but it doesn't work.

Logs from console pod:
```bash
2022/01/13 20:50:50 Post "https://minio-console.minio.svc.cluster.local:9443/api/v1/login": dial tcp: lookup minio-console.minio.svc.cluster.local on 10.233.0.3:53: no such host
2022/01/13 20:50:52 Post "https://minio-console.minio.svc.cluster.local:9443/api/v1/login": dial tcp: lookup minio-console.minio.svc.cluster.local on 10.233.0.3:53: no such host
```

**Comment by harshavardhana** [comment]
> I found that [operatorapi/proxy.go#L95](https://github.com/minio/console/blob/bbe87ecd599319f5575cd1aae021685d444d076a/operatorapi/proxy.go#L95) calls function `GetClusterDomain()`. I've tried setting the environment variable `clusterDomain` that is used by [v2.GetClusterDomain()](https://github.com/minio/operator/blob/049906f88ad0e81c4d42c7407ca2ad7f5bad9915/pkg/apis/minio.min.io/v2/helper.go#L930) manually in the deployment.yaml but it doesn't work.

Please share how you set it @vincentbaeten

**Comment by dvaldivia** [comment]
@vincentbaeten do you see the `CLUSTER_DOMAIN` environment variable set on the `console` deployment in the `minio-operator` namespace?

**Comment by vincentbaeten** [comment]
No I do not. I've tried setting the env variable to `CLUSTER_DOMAIN` and `CLUSTERDOMAIN` manually too but without any luck.

**Comment by vincentbaeten** [comment]
Also I forgot to mention that I'm using operator v4.4.3 which uses console v.0.13.2

**Comment by harshavardhana** [comment]
I see that operator has it set properly

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
  name: minio-operator
  namespace: minio-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: minio-operator
  template:
    metadata:
      annotations:
        operator.min.io/authors: MinIO, Inc.
        operator.min.io/license: AGPLv3
        operator.min.io/support: https://subnet.min.io
      labels:
        name: minio-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - minio-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: CLUSTER_DOMAIN
          value: test.local
        image: minio/operator:v4.4.3
        imagePullPolicy: IfNotPresent
        name: minio-operator
        resources:
          requests:
            cpu: 200m
            ephemeral-storage: 500Mi
            memory: 256Mi
        securityContext:
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
      serviceAccountName: minio-operator
```
