### ISSUE TITLE
Web console stuck on `/buckets` page with bucket-specific policy

### ISSUE THREAD

**Issue by guzman-raphael** [minio/console#1522]
First off, a big thank you for all the amazing contributions to this project! :handshake:

Not sure if this is the right place to report this issue or if it is simply a configuration issue on my side. :sweat_smile:
Any help to resolve this or repoint to a more suitable place is much appreciated.

I encountered an issue when restricting a user's access to just a specific bucket i.e. I'm looking for a solution where the user cannot even *see* other buckets other than `vathes.com` within the browser console. I've come up with the following policy applied to a test user and confirmed it works using the MinIO Python SDK. `s3:ListBucket` seems to allow listing the buckets, `s3:GetBucketLocation` seems to allow listing the objects, and `s3:GetObject` seems to allow downloading the objects all appropriately contained within the `vathes.com` bucket.

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation",
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::vathes.com*"
      ],
      "Sid": ""
    }
  ]
}
```

However, when I access this through the MinIO Browser Console, I am unable to get past the bucket screen (see below). Is there something I'm doing wrong or could this be a bug? I was looking into setting up a development environment to help troubleshoot, but I see that the image has a production optimized build for the frontend so Chrome's DevTools debugger wasn't available. If there is any docs that can help set that up, I can certainly help to debug/patch this if it is an issue.

https://user-images.githubusercontent.com/38401847/152659986-90063f06-4d12-4cc0-9786-0aeb84a6fb42.mov

Running this in a docker environment as follows:

```yaml
# docker-compose up --build
version: '2.4'
services:
  minio:
    image: minio/minio:RELEASE.2022-02-01T18-00-14Z
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    entrypoint:
      - bash
      - -c
    command:
      - |
        set -e
        # start gateway
        /usr/bin/docker-entrypoint.sh gateway s3 --console-address ":9001" &
        # install mc
        curl -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x /usr/local/bin/mc
        # configure minio connection
        mc config host add dj-gateway http://localhost:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        # add policy
        mc admin policy add dj-gateway wf-guest /tmp/policies/wf-guest.json
        # add user
        mc admin user add dj-gateway raphael password1
        # create/add-to group
        mc admin group add dj-gateway wf-guest raphael
        # attach policy
        mc admin policy set dj-gateway wf-guest group=wf-guest
        # stay attached
        tail -f /dev/null
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./policies:/tmp/policies
```
