### ISSUE TITLE
Lost displaying volumes and disk space UI

### ISSUE THREAD

**Issue by moracabanas** [minio/console#1629]
When I was testing minio I arranged a 4 volumes setup to get erasure code.

I found a UI menu on console where I could check space and display available volumes but now I just cannot find it. I just get the metrics data from Monitoring > metrics. But there is not the display I found before.

Could you get me more insights about this issue? Thanks you!

**Comment by harshavardhana** [comment]
Please elaborate further on your setup @moracabanas - there is nothing that you are talking here helps us help you.

**Comment by moracabanas** [comment]
I am testing a minio deployment with the next `docker-compose.yaml`:

```yaml
version: "3.4"

services: 
  # minio service
  minio:
    image: minio/minio
    container_name: minio
    # ports on reverse proxy not exposed directly
    # ports:
    #   - "9000" # S3
    #   - "9001" # Console
    volumes:
      - /media/pi/data1:/data1
      - /media/pi/data2:/data2
      - /media/pi/data3:/data3
      - /media/pi/data4:/data4

    environment:
      # - MINIO_ACCESS_KEY=********************************
      # - MINIO_SECRET_KEY=********************************
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL=http://prometheus:9090
    command: 'server /data{1...4} --console-address ":9001"'
  
  prometheus:
    ...
  reverse-proxy:
    ...
```

Everything is working as expected but I can't found a console UI view where it used to display `data1` `data2` `data3` & `data4` disks and the total usable space in a pie chart (not in prometheus metrics)
