### ISSUE TITLE
Minio console is not exposed correctly on subpath

### ISSUE THREAD

**Issue by jekel** [minio/console#1909]
Hello,
i'm using latest minio docker image minio/minio:RELEASE.2022-04-26T01-20-24Z
with configs of docker-compose
```
  minio:
    image: minio/minio:RELEASE.2022-04-26T01-20-24Z
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_BROWSER_REDIRECT_URL: "https://MYEXTERNALDOMAIN/minio-console/"
    command: server /data --console-address ":9001"
    restart: always
 ```
and nginx on host machine
```
    location /minio-console/ {
        rewrite ^/minio-console/(.*)$ /$1 break;
        proxy_pass http://localhost:9001;
    }
```
after opening  main console URL - https://MYEXTERNALDOMAIN/minio-console/ browser is redirected(i think via JS, not http headers) to 
https://MYEXTERNALDOMAIN/minio-console/minio-console/login

so, i think fix https://github.com/minio/minio/pull/14761  does not work correctly
