### ISSUE TITLE
MINIO_PROMETHEUS_JOB_ID env is not applied

### ISSUE THREAD

**Issue by ryuseongryong** [minio/console#1925]
Hello
I'm experiencing no dashboard data problem(e.g. https://github.com/minio/console/issues/1065, https://github.com/minio/console/issues/787, https://github.com/minio/console/issues/799)

exactly, almost same https://github.com/minio/console/issues/1065 case. without tls setting.

and I found the primary cause.
MINIO_PROMETHEUS_JOB_ID setting is not applied.

I set up as K8S with minio-operator and minio-tenant for minio, with prometheus podmonitor for monitoring.
according to the official doc(https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html ) says to define the environment variale like this.

```
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
    - name: MINIO_PROMETHEUS_URL
      value: http://prometheus-operated.prometheus.svc.cluster.local:9090
    - name: MINIO_PROMETHEUS_JOB_ID
      value: prometheus/minio-metrics-exporter
```

I also define as.
but 
```
$ kubectl exec -it -n minio service/minio-console -- printenv | grep MINIO_PROMETHEUS
MINIO_PROMETHEUS_AUTH_TYPE=public
MINIO_PROMETHEUS_URL=http://prometheus-operated.prometheus.svc.cluster.local:9090
MINIO_PROMETHEUS_JOB_ID=minio-minio-job
```
My guess is that there is a process of setting up the minio somewhere else.
If you have any guesses on what part it is, please let me know.
(one more, The strange thing is that it's not set to minio-job, it's set to minio-minio-job.)

**Comment by harshavardhana** [comment]
where you prometheus running? @ryuseongryong

**Comment by ryuseongryong** [comment]
@harshavardhana  on k8s, with prometheus, podmonitor but other namespace

**Comment by harshavardhana** [comment]
> @harshavardhana on k8s, with prometheus, podmonitor but other namespace

can you capture your prometheus configuration? and share it here?

**Comment by ryuseongryong** [comment]
minio tenant, with minio-operator(`kubectl minio init`)
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  labels:
    app: minio
spec:
  credsSecret:
    name: minio-secret
  pools:
    - servers: 2
      volumesPerServer: 2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - minio
              topologyKey: kubernetes.io/hostname
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 32G
  requestAutoCert: false
  # prometheusOperator: true
  env:
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
    - name: MINIO_PROMETHEUS_URL
      value: http://prometheus-operated.prometheus.svc.cluster.local:9090
    - name: MINIO_PROMETHEUS_JOB_ID
      value: prometheus/minio-metrics-exporter
    - name: MINIO_PROMETHEUS_JOB_ID
      value: prometheus/minio-metrics-exporter

```
prometheus - podmonitor
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: minio-metrics-exporter
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: minio
  namespaceSelector:
    matchNames:
      - minio
  podMetricsEndpoints:
    - path: /minio/v2/metrics/cluster
      targetPort: 9000
```

**Comment by ryuseongryong** [comment]
@harshavardhana maybe, It's just minio environment variable setting problem, I think..
It's working as grafana dashboard from minio(https://grafana.com/grafana/dashboards/13502) and also prometheus is working query well with minio prefix.

minio-console dashboard is connecting with prometheus but, MINIO_PROMETHEUS_JOB_ID is not applied.
```
$ kubectl edit tenants.minio.min.io -n minio
...
env:
  - name: MINIO_PROMETHEUS_AUTH_TYPE
     value: public
  - name: MINIO_PROMETHEUS_URL
     value: http://prometheus-operated.prometheus.svc.cluster.local:9090
  - name: MINIO_PROMETHEUS_JOB_ID
     value: prometheus/minio-metrics-exporter
```
but deployed MINIO_PROMETHEUS_JOB_ID of minio env is just minio-minio-job

**Comment by harshavardhana** [comment]
> - name: MINIO_PROMETHEUS_JOB_ID
>      value: prometheus/minio-metrics-exporter

This is a wrong prometheus Job_id - please share the prometheus.yaml file generated inside the prometheus pods

**Comment by ryuseongryong** [comment]
@harshavardhana This one?

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: ['']
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources:
      - configmaps
    verbs: ['get']
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ['get', 'list', 'watch']
  - nonResourceURLs: ['/metrics']
    verbs: ['get']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  replicas: 1
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      app: prometheus
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  additionalScrapeConfigs:
    name: additional-scrape-config
    key: additional-scrape-config.yaml
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi

```
