### ISSUE TITLE
Ingress Path Not Working.

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [minio/console#2045]

**Comment by Sam-Sundar-Apty** [comment]
Thanks a lot @harshavardhana,

If possible, can you try to reproduce on Kubernetes and ingress ? Or with subpath on compose and Nginx.

Since, main domain will reach out to our app and /minio should reach minio. This used to work with 2021 July version, before the update to this UI version.

**Comment by Subetov** [comment]
One more question - does the MINIO_CONSOLE_SUBPATH variable no longer work?
It seems that only MINIO_BROWSER_REDIRECT_URL works.
But I do not want to specify a hostname, I want my ingress to listen to any hostname.
Like:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: minio-console
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: minio-console
            port:
              number: 9001
        path: /minio/(/|$)(.*)
        pathType: Prefix
```

```
 spec:
      containers:
      - args:
        - server
        - /data
        - --console-address
        - :9001
        env:
        - name: CONSOLE_SUBPATH
          value: /minio
        - name: MINIO_CONSOLE_SUBPATH
          value: /minio
        - name: MINIO_BROWSER
          value: "on"
```
Thanks !

**Comment by Subetov** [comment]
@dvaldivia , yes.
Sorry to hear that =(
MINIO_CONSOLE_SUBPATH was very useful.
A lot of people use it without a specific domain.
In order to cover all possible domains with ingress.

**Comment by jmthomas** [comment]
I too was hoping for a solution that simply allowed me to set a subpath. I have existing traefik rules that are matching all the console assets and prevent it from loading. Simply adding a subpath would be perfect for me. How can having a full domain work in both development and production? None of my existing docker-compose or traefik rules specify a domain. Please bring back SUBPATH!

**Comment by jmthomas** [comment]
Turns out the domain doesn't really matter if you're using something like traefik. I set mine to `MINIO_BROWSER_REDIRECT_URL: "http://openc3.com/minio"` and then in my traefik.yaml rule I created a router to push files to that service:

    http:
      middlewares:
        # Removes the first part of the url before passing onto the service
        removeFirst:
          replacePathRegex:
            regex: "^/([^/]*)/(.*)"
            replacement: "/$2"
      routers:
        minio-console:
          rule: PathPrefix(`/minio`)
          middlewares:
            # remove /minio from the beginning
            - "removeFirst"
          service: service-minio-console
      services:
        # The Minio S3 console
        service-minio-console:
          loadBalancer:
            passHostHeader: false
            servers:
              - url: "http://openc3-minio:9001"

I'm also setting the console address in my compose.yaml with the following minio command:

    command: server --address ":9000" --console-address ":9001" /data

**Comment by mcooknu** [comment]
Assuming I want to use a subpath for the operator (or tenant) console and I dont rewrite the path before hitting the console.

What are the provisioning steps when installing minio-operator via helm (4.4.28) which uses 0.19.4.
I see the support subpath in console code base is in console v0.19.2 but I am not sure what steps I should take defining ENVs with the subpath I wish to use on the ingress.

Do I need to set MINIO_CONSOLE_SUBPATH?
(I have tried setting MINIO_BROWSER_REDIRECT_URL)
```
console:
  image:
    repository: minio/console
    tag: v0.19.4
    pullPolicy: IfNotPresent
  imagePullSecrets: [ ]
  initcontainers: [ ]
  replicaCount: 1
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  topologySpreadConstraints: [ ]
  resources: { }
  env:
    - name: MINIO_CONSOLE_SUBPATH
      value: "/minio/operator/"
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  ingress:
    enabled: true
    ingressClassName: ""
    labels: { }
    annotations: { }
    tls: [ ]
    host: localhost
    path: /minio/operator/
    pathType: Prefix
  volumes: [ ]
  volumeMounts: [ ]
```

I can reach the operator console fine via kubectl proxy but I would like to reach it via http://localhost/minio/operator and then similarly the console for tenant-1, http://localhost/minio/tenant-1/.

In both instances, I can read the operator console but it is not using a subpath and attempts to load most of the page from non-existing "root" subpath location.

Appreciate any help, I've spent way too many hours trying to follow old documentation with new charts & releases. :/

**Comment by vmire** [comment]
Subpath works for me except for download links, which ignores it.

I use the latest docker image (minio/minio:latest)
Environment :
```
MINIO_BROWSER_REDIRECT_URL: 'http://localhost:8080/minio/'
```
Reverse proxy rewrite : 
```
"proxy-rewrite": {
      "regex_uri": [
        "^/minio/(.*)",
        "/$1"
      ]
    }
```

Console URL : http://localhost:8080/minio/
=> works fine
Generated download link example : http://localhost:8080/api/v1/buckets/orgo/objects/download?prefix=ZmlsZXMvU3ludGglQzMlODMlQzIlQThzZSUyMGRlJTIwR2FyYW50aWVzLTIucGRm&version_id=null
=> doesn't work : subpath is missing


I appreciate any help

**Comment by dvaldivia** [comment]
@vmire that sounds a like a simple bug to fix, can you file a separate issue for that?

**Comment by liolay** [comment]
we also need subpath rather than MINIO_BROWSER_REDIRECT_URL,  this environment parameter is very inflexible !

**Comment by jarrettprosser** [comment]
I am running into the same issue configuring an ingress subpath. Though I have MINIO_BROWSER_REDIRECT_URL configured, the console is still serving resources at `/` and so I get the same loading errors that @Sam-Sundar-Apty showed in the original post. This is with minio image RELEASE.2022-10-29T06-21-33Z and the minio helm chart 5.0.0.

**Comment by usersina** [comment]
I also have the same issue configuring Ingress console access with [this helm chart](https://github.com/minio/minio/tree/master/helm/minio).

```yml
consoleIngress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: app-clusterissuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /minio(/|$)(.*)
  hosts:
    - my.application.com
  tls:
    - secretName: app-certificate-secret
      hosts:
        - my.application.com
```

**Comment by MdShimulMahmud** [comment]
> Hey Team,
> 
> I'm trying to upgrade from old version of MinIo to latest one and we found we had to make multiple changes,
> 
>     spec:
>       containers:
>       - args:
>         - server
>         - /storage
>         - --console-address
>         - :9001
>         env:
>         - name: MINIO_ROOT_USER
>           value: minio
>         - name: MINIO_ROOT_PASSWORD
>           value: minio123
>         #- name: MINIO_BROWSER_REDIRECT_URL
>         #  value: https://onprem-test.development.apty.io
>         image: minio/minio:latest
>         imagePullPolicy: IfNotPresent
>         name: minio
>         ports:
>         - containerPort: 9000
>           name: api-port
>           protocol: TCP
>         - containerPort: 9001
>           name: console-port
>           protocol: TCP
>         resources:
> 
> This is my svc definition
> 
> minio-api-service         NodePort    10.96.1.117   <none>        9000:31822/TCP                  29m
> minio-service             NodePort    10.96.0.155   <none>        9001:31823/TCP                  38d
> 
> This is my ingress file
> 
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   projectcontour.io/response-timeout: infinity
>   name: https-ingress
>   namespace: default
> spec:
>   rules:
>   - host: onprem-test.development.apty.io
>     http:
>       paths:
>       - backend:
>           service:
>             name: minio-service
>             port:
>               number: 9001
>         path: /minio/
>         pathType: Prefix
>   tls:
>   - hosts:
>     - onprem-test.development.apty.io
>     secretName: apty-onprem
> status:
>   loadBalancer: {}
> 
> When i try to hit /minio, it's not opening console
> 
> ![image](https://user-images.githubusercontent.com/83000807/170481711-41fa07c4-fa78-4ca9-b6f8-cc815867e254.png)

Here’s a clean and organized configuration to deploy MinIO as a StatefulSet and expose its console under /minio or /minio1 subpaths using Nginx Ingress:

**1. MinIO StatefulSet Configuration**

Configure MinIO to recognize it’s being served under a subpath using environment variables:

```yaml
# minio-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: testing
spec:
  serviceName: minio-svc  # Matches the Service name
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address ":9090"
        env:
        - name: MINIO_BROWSER_REDIRECT_URL  # Critical for subpath support
          value: "http://minio-svc.testing.svc.cluster.local/minio/"
        ports:
        - containerPort: 9000  # S3 API Port
        - containerPort: 9090  # Console Port
        readinessProbe:
          httpGet:
            path: /minio/health/ready  # Subpath-aware health check
            port: 9090
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9090
```

**2. Service Configuration**

Expose both the S3 API (9000) and Console (9090):
```yaml
# minio-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: testing
spec:
  selector:
    app: minio
  ports:
  - name: s3
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
```

**3. Ingress Configuration**

Route traffic to the /minio subpath and rewrite URLs correctly:

```yaml
# minio-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-ns-ingress-service
  namespace: testing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1  # Strip "/minio" prefix
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  ingressClassName: nginx-testing-ns
  rules:
  - http:
      paths:
      - path: /minio/?(.*)  # Capture paths after "/minio/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-svc  # Matches the Service name
            port:
              number: 9090   # Console port
```

1. ```MINIO_BROWSER_REDIRECT_URL```

    Purpose: Tells MinIO to generate URLs with the ```/minio``` subpath (e.g., ```/minio/login ``` instead of ```/login```).

    Format: ```http://<service-name>.<namespace>.svc.cluster.local/<subpath>/```

    Example:
```yaml
value: "http://minio-svc.testing.svc.cluster.local/minio/"
```

2. ```Ingress rewrite-target```

    Behavior: Strips the ```/minio/``` prefix from requests before forwarding to MinIO.
    Example:
    ```http://<external-ip>/minio/``` → MinIO receives ```/login```.

**Comment by MdShimulMahmud** [comment]
Here’s a clean and organized configuration to deploy MinIO as a StatefulSet and expose its console under /minio or /minio1 subpaths using Nginx Ingress:

**1. MinIO StatefulSet Configuration**

Configure MinIO to recognize it’s being served under a subpath using environment variables:

```yaml
# minio-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: testing
spec:
  serviceName: minio-svc  # Matches the Service name
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address ":9090"
        env:
        - name: MINIO_BROWSER_REDIRECT_URL  # Critical for subpath support
          value: "http://minio-svc.testing.svc.cluster.local/minio/"
        ports:
        - containerPort: 9000  # S3 API Port
        - containerPort: 9090  # Console Port
        readinessProbe:
          httpGet:
            path: /minio/health/ready  # Subpath-aware health check
            port: 9090
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9090
```

**2. Service Configuration**

Expose both the S3 API (9000) and Console (9090):
```yaml
# minio-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: testing
spec:
  selector:
    app: minio
  ports:
  - name: s3
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
```

**3. Ingress Configuration**

Route traffic to the /minio subpath and rewrite URLs correctly:

```yaml
# minio-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-ns-ingress-service
  namespace: testing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1  # Strip "/minio" prefix
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  ingressClassName: nginx-testing-ns
  rules:
  - http:
      paths:
      - path: /minio/?(.*)  # Capture paths after "/minio/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-svc  # Matches the Service name
            port:
              number: 9090   # Console port
```

1. ```MINIO_BROWSER_REDIRECT_URL```

    Purpose: Tells MinIO to generate URLs with the ```/minio``` subpath (e.g., ```/minio/login ``` instead of ```/login```).

    Format: ```http://<service-name>.<namespace>.svc.cluster.local/<subpath>/```

    Example:
```yaml
value: "http://minio-svc.testing.svc.cluster.local/minio/"
```

2. ```Ingress rewrite-target```

    Behavior: Strips the ```/minio/``` prefix from requests before forwarding to MinIO.
    Example:
    ```http://<external-ip>/minio/``` → MinIO receives ```/login```.

@Sam-Sundar

**Comment by MdShimulMahmud** [comment]
> Hey Team,
> 
> I'm trying to upgrade from old version of MinIo to latest one and we found we had to make multiple changes,
> 
>     spec:
>       containers:
>       - args:
>         - server
>         - /storage
>         - --console-address
>         - :9001
>         env:
>         - name: MINIO_ROOT_USER
>           value: minio
>         - name: MINIO_ROOT_PASSWORD
>           value: minio123
>         #- name: MINIO_BROWSER_REDIRECT_URL
>         #  value: https://onprem-test.development.apty.io
>         image: minio/minio:latest
>         imagePullPolicy: IfNotPresent
>         name: minio
>         ports:
>         - containerPort: 9000
>           name: api-port
>           protocol: TCP
>         - containerPort: 9001
>           name: console-port
>           protocol: TCP
>         resources:
> 
> This is my svc definition
> 
> minio-api-service         NodePort    10.96.1.117   <none>        9000:31822/TCP                  29m
> minio-service             NodePort    10.96.0.155   <none>        9001:31823/TCP                  38d
> 
> This is my ingress file
> 
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   projectcontour.io/response-timeout: infinity
>   name: https-ingress
>   namespace: default
> spec:
>   rules:
>   - host: onprem-test.development.apty.io
>     http:
>       paths:
>       - backend:
>           service:
>             name: minio-service
>             port:
>               number: 9001
>         path: /minio/
>         pathType: Prefix
>   tls:
>   - hosts:
>     - onprem-test.development.apty.io
>     secretName: apty-onprem
> status:
>   loadBalancer: {}
> 
> When i try to hit /minio, it's not opening console
> 
> ![image](https://user-images.githubusercontent.com/83000807/170481711-41fa07c4-fa78-4ca9-b6f8-cc815867e254.png)

@Sam-Sundar 
Here’s a clean and organized configuration to deploy MinIO as a StatefulSet and expose its console under /minio or /minio1 subpaths using Nginx Ingress:

**1. MinIO StatefulSet Configuration**

Configure MinIO to recognize it’s being served under a subpath using environment variables:

```yaml
# minio-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: testing
spec:
  serviceName: minio-svc  # Matches the Service name
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address ":9090"
        env:
        - name: MINIO_BROWSER_REDIRECT_URL  # Critical for subpath support
          value: "http://minio-svc.testing.svc.cluster.local/minio/"
        ports:
        - containerPort: 9000  # S3 API Port
        - containerPort: 9090  # Console Port
        readinessProbe:
          httpGet:
            path: /minio/health/ready  # Subpath-aware health check
            port: 9090
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9090
```

**2. Service Configuration**

Expose both the S3 API (9000) and Console (9090):
```yaml
# minio-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: testing
spec:
  selector:
    app: minio
  ports:
  - name: s3
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090
```

**3. Ingress Configuration**

Route traffic to the /minio subpath and rewrite URLs correctly:

```yaml
# minio-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-ns-ingress-service
  namespace: testing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1  # Strip "/minio" prefix
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  ingressClassName: nginx-testing-ns
  rules:
  - http:
      paths:
      - path: /minio/?(.*)  # Capture paths after "/minio/"
        pathType: ImplementationSpecific
        backend:
          service:
            name: minio-svc  # Matches the Service name
            port:
              number: 9090   # Console port
```

1. ```MINIO_BROWSER_REDIRECT_URL```

    Purpose: Tells MinIO to generate URLs with the ```/minio``` subpath (e.g., ```/minio/login ``` instead of ```/login```).

    Format: ```http://<service-name>.<namespace>.svc.cluster.local/<subpath>/```

    Example:
```yaml
value: "http://minio-svc.testing.svc.cluster.local/minio/"
```

2. ```Ingress rewrite-target```

    Behavior: Strips the ```/minio/``` prefix from requests before forwarding to MinIO.
    Example:
    ```http://<external-ip>/minio/``` → MinIO receives ```/login```.
