### ISSUE TITLE
Trouble in Accessing minIO console through Virtual Service 

### ISSUE THREAD

**Issue by ashujain2** [minio/console#2149]
## Issue :-

I have deployed minio into EKS cluster now my aim is to create virtual-service and using prefix defined into VS ,User should be able login into minio-console UI.

Post creation of VS , I am getting Response from URL -http://localhost:3100/source-cserver/ with Status Code: 200 OK
but webpage is not getting opened up .

## Expected Behavior :- 

User will click into URL http://localhost:3100/source-cserver/ and minio console UI should open.

## Current Behavior

When we try to hit uri with prefix source-cserver then it goes to minio-console somehow (Infact, status code is 200 ok ) but page is blank with 3 blocks.

<img width="960" alt="Webpage-Status" src="https://user-images.githubusercontent.com/92740219/175947962-bffc39fd-0758-49bc-90be-6a13317a1c31.png">

## Desired Output

When Port is being forwarded through LENS / or kubectl port-forward pods/console-XXXXXXX -n=source-cserver
I got the desired result , similar expectation I aim to achieve by creating virtual service

<img width="902" alt="minio-console" src="https://user-images.githubusercontent.com/92740219/175948219-71942bda-6189-4737-afda-b35a91251e46.png">

## Steps to Reproduce 

**VirtualService**-

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: minio-console
    app.kubernetes.io/component: server
    app.kubernetes.io/name: minio
  annotations:
    sidecar.istio.io/inject: "false"
  name: minio-console
  namespace: source-cserver
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - '*'
  http:
    - retries:
        attempts: 3
        perTryTimeout: 2s
      match:
        - uri:
            prefix: /source-cserver/
      route:
        - destination:
            host: source-cserver-console.source-cserver.svc.cluster.local
            port:
              number: 9090
```

**Comment by asianman35** [comment]
I am having this same issue, can you post your Istio Virtual Service that is working @j13tw ?

**Comment by j13tw** [comment]
@asianman35 
Sorry that late to reply it, 
As I know the latest version is fixed the download error, 
and Fix Logout not used subpath issue (after my report it).
A simple sample for latest version MinIO Console, 
If you needed to used the locked or old MinIO version, 
You can research error on browser web-console (F12) -> Network to saw Console API, 
and then hot to fix it with the Istio VS.
FYI.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: custom-minio-vs
  namespace: istio-system
spec:
  gateways: 
  - custom-minio-gw
  hosts:
  - "minio.anywhere.com"
  http:
  - name: "minio-console"
    match:
    - uri:
        prefix: "/minio-console/"
    - uri:
        exact: "/minio-console"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: minio-console.minio.svc.cluster.local
        port:
          number: 9001
```
