### ISSUE TITLE
Some troubles when first time to start the Minio Server using Docker

### ISSUE THREAD

**Issue by rsyanting** [minio/console#2200]
hi , every one.

Last night, I just using docker-compose to start a Minio server standalone.

When I try to using the Web Console, I got some troubles, and without logs, I don't know what happend.

Here is my docker-compose.yaml

```yaml
version: '3.6'

services:
  minio:
    container_name: "minio"
    image: minio/minio:RELEASE.2022-07-24T01-54-52Z
    ports:
      - "59000:9000/tcp" # api 端口
      - "59001:9001/tcp" # 控制台端口
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: duwi373dywbs283gs82    #管理后台用户名
      MINIO_ROOT_PASSWORD: 39UEY2dje823_383#2UE72g272t283 #管理后台密码，最小8个字符
    volumes:
      - /home/ubuntu/minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - /home/ubuntu/minio/config:/root/.minio/     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always
```

I using the command: `docker-compose up -d ` to start the container.

and I just check th iptables, the port of `59000` and `59001` is open.

When I visit the Minio Console, the UI is like this, I have no idea what happend.

![Snipaste_2022-07-24_21-35-20.png](https://s2.loli.net/2022/07/26/yGguLCcESis6Ffn.png)

what's MORE, when I using the latest images: `RELEASE.2022-07-24T17-09-31Z `, every thing is ok.....

**Did I do some thing wrong?** 

My team want to using your product, but now we don't know what to do, we both got confuse ……

Thanks for your reading and helping.
