### ISSUE TITLE
same JWT not work for login operator console, get 401 unauthenticated for invalid credentials 

### ISSUE THREAD

**Issue by qwegas** [minio/console#2610]
just install and create a nodeport svc to login it

```
helm install minio-operator  operator-4.5.7.tgz -n minio-operator --create-namespace
```

apply 
```
apiVersion: v1
kind: Service
metadata:
  name: console-nodeport
  namespace: minio-operator
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  type: NodePort

---

apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
```

get jwt

```
kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode
```
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/8144089/215255454-7e99b8d7-cd75-4158-8eb0-5be27604fd44.png">

console log
```
Serving operator at http://[::]:9090
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
```

At the first time，it can login the operator console  
- and then install tenant  by helm 
- maybe the login timeout and refresh  to the login page.
- use same jwt to login 
- get same error

<img width="943" alt="image" src="https://user-images.githubusercontent.com/123848894/215311124-94d3b48a-f70a-463b-858b-29a94c3881e6.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/123848894/215311137-645b61e2-716d-4b83-9e72-de10b9aa13c2.png">

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/123848894/215311149-2df85ee9-a63a-4215-b840-67629d9ed9eb.png">

## Your Environment

* Version used (`minio-operator`):  4.5.7
* Environment name and version (e.g. kubernetes v1.17.2):  1.23.6
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:
