### ISSUE TITLE
MinIO Console Subpath Failing to load 

### ISSUE THREAD

**Issue by surya-apty** [minio/console#3091]
Need help setting MinIO ingress 

when trying to open https://mydomain.io/minio/console unable to load it.

below is my Deployment, Ingress and Service Configuration 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  annotations:
    backup.velero.io/backup-volumes: storage  
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
          - /bin/bash
          - -c
          args: 
          - minio server /storage3/storage3 --address :9000 --console-address :9090
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1200Mi
            requests:
              cpu: 300m
              memory: 700Mi
          env:
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              value: "minio123"
            # - name: MINIO_CONSOLE_SUBPATH
            #   value: /minio/console/
            - name: MINIO_BROWSER_REDIRECT_URL
              value: https://mydomain.io/minio/console
          ports:
            - containerPort: 9000
              protocol: TCP
              name: minio-service
            - containerPort: 9090
              protocol: TCP
              name: minio-console
          volumeMounts:
            - name: storage
              mountPath: "/storage3"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage-volume-claim-4                
      imagePullSecrets:
        - name: dockerhub
---
apiVersion: v1
kind: Service 
metadata:
  name: minio-service
spec:
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app:
      minio
---
apiVersion: v1
kind: Service 
metadata:
  name: minio-console
spec:
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app:
      minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    projectcontour.io/response-timeout: infinity
  name: minio-ingress
spec:
  rules:
  - host: mydomain.io
    http:
      paths:
      - backend:
          service:
            name: minio-console
            port:
                  number: 9090
        path: /minio/console
        pathType: Prefix
      - backend:
          service:
            name: minio-service
            port:
                  number: 9000
        path: /minio
        pathType: Prefix
  tls:
  - hosts:
    - mydomain.io
    secretName: test
```
