### ISSUE TITLE
Minio console login error

### ISSUE THREAD

**Issue by nickuntip** [minio/console#3110]
## NOTE
Minio doesn't open login form over https after migration from RELEASE.2020-12-10T01-54-29Z to RELEASE.2023-03-20T20-16-18Z.
Instead it shows an error message:

"An error has occurred
The backend cannot be reached."

I have host with installed docker containers, one of them is MinIO, one is Nginx

Tried with several MinIO versions i.e. RELEASE.2023-10-25T06-33-25Z, RELEASE.2022-10-24T18-35-07Z

## Expected Behavior

![image](https://github.com/minio/console/assets/149383598/174c42cd-4b46-4b80-a332-19bb0bdfb6c7)

## Current Behavior

![image](https://github.com/minio/console/assets/149383598/09b11959-a51f-4daa-af60-f4b9318f6a6b)

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Create the following docker-compose.yaml file and launch it docker-compose up. Make sure no other process is on ports 9051 and 9050.

```
version: '2.4'
services:
  minio:
    container_name: minio_clear
    network_mode: "host"
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    restart: always
    volumes:
      - /mnt/data_clear:/mnt/data
      - /opt/minio/keys:/root/.minio/certs
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      
    command: server --address :9050 --console-address ":9051" /mnt/data
    expose:
      - "9050"
      - "9051"
```

2. Create Nginx container owasp/modsecurity:3.0.3-nginx, set nginx.conf
`
# Upstreams

    upstream minio_servers {
        ip_hash;
        server hostname.example.org:9051 max_fails=1 fail_timeout=10s;
    }

# Servers

    server {
        listen              443 ssl;
        server_name         hostname.example.org;
        ssl_certificate     /etc/pki/tls/certs/cert.crt;
        ssl_certificate_key /etc/pki/tls/certs/cert.key;
        ssl_password_file   /etc/pki/tls/certs/nginx_passphrase;

        # Minio
        location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;

            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Origin '';
            chunked_transfer_encoding off;

            proxy_pass http://minio_servers;
            proxy_next_upstream error timeout invalid_header http_500 http_503 http_504 http_502;
        }
    }`

## Regression

Yes, worked in RELEASE.2020-12-10T01-54-29Z

## Your Environment

* MinIO version used (`minio --version`): RELEASE.2023-03-20T20-16-18Z
* Server setup and configuration: Docker version 19.03.10, build 9424aeaee9
* Operating System and version (`uname -a`): 3.10.0-1127.el7.x86_64
