### ISSUE TITLE
MInio console UI page refresh issue 

### ISSUE THREAD

**Issue by balaKarur** [minio/console#3274]
## NOTE

Hello All,
**Issue**:
Getting refresh issue while access minio Console UI, Please refer attached image...
I faced this issue in both minio (windows and linux version )
To check minio windows version : [https://min.io/download#/agpl-windows]

## Expected Behavior

while access minio console UI , logion page has to shown ,without multiple refresh .
[http://localhost:9001/](url)
## Current Behavior

Need to refresh many time to get login page , after login successful , again need to refresh many time to get landing page 

## Possible Solution

Need a suggestion to fix this 
**## Steps to Reproduce (for bugs)**

This is windows minio ,
https://min.io/download#/agpl-windows
 Just download and run the server you will face refresh issue while access the URL 
[http://localhost:9001/](url)

**## Context**

I need to use minio server, for to upload files under bucket .
**## Regression**

I think .its Regression, and straightforward issue 
## Your Environment

* MinIO version used (`minio --version`): RELEASE.2024-03-21T23-13-43Z
* Server setup and configuration:
* Operating System and version (`uname -a`): ubuntu20 access thur wsl
**This my setup :**
**I am using latest keycloak and minio service
I followed to**
1)Configure MinIO for Authentication using Keycloak
https://min.io/docs/minio/linux/operations/external-iam/configure-keycloak-identity-management.html
2)https://min.io/docs/minio/linux/reference/minio-server/settings/iam/openid.html#redirect-uri
This is my yaml file
version: "3.8"
services:
    minio:
        image: [quay.io/minio/minio:RELEASE.2024-03-21T23-13-43Z](http://quay.io/minio/minio:RELEASE.2024-03-21T23-13-43Z)
        container_name: minio
        volumes:
          - ./minio_data:/data
        command: server /data --console-address=":9001"
        ports:
          - 9000:9000
          - 9001:9001
        environment:
          - MINIO_ROOT_USER=admin
          - MINIO_ROOT_PASSWORD=password
          - MINIO_SERVER_URL=http://localhost:9000/
          - MINIO_DOMAIN=http://localhost:9000/
          - MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY=http://host.containers.internal:8088/kc/realms/demorealm/.well-known/openid-configuration
          - MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY=minio
          - MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY=SymWPBfZVz4qJoC7MevG63Sat
          - MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY=MinIO OpenID Login
          #- MINIO_IDENTITY_OPENID_SCOPES_KEYCLOAK_PRIMARY=openid,preferred_username
          - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
          - MINIO_IDENTITY_OPENID_VENDOR=keycloak
          - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY=on
          - MINIO_IDENTITY_OPENID_SCOPES=minio-authorization
          - MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=demorealm
          - MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://host.containers.internal:8088/kc/admin
          #- MINIO_BROWSER_REDIRECT_URL=http://localhost:9000/minio-console
    #      - CONSOLE_SUBPATH=/minio-console
          #- CONSOLE_MINIO_SERVER=http://localhost:9000/
          #- MINIO_API_SELECT_PARQUET=on
        # restart: always
volumes:
    minio_data: (edited)
![refresh](https://github.com/minio/console/assets/13732401/20a77eb0-b7a5-4a0a-8463-1718d2f23681)

**Comment by cesnietor** [comment]
@balaKarur  could you please share your keycloak configuration, there might be an issue there. 
cc @adriangitvitz

**Comment by balaKarur** [comment]
Hello @cesnietor 
i am getting issue without keycloak integration also

I tried with windows version from below URL
https://min.io/download#/agpl-windows

_By following these steps :_
**PS> Invoke-WebRequest -Uri "https://dl.min.io/server/minio/release/windows-amd64/minio.exe" -OutFile "C:\minio.exe"
PS> setx MINIO_ROOT_USER admin
PS> setx MINIO_ROOT_PASSWORD password
PS> C:\minio.exe server F:\Data --console-address ":9001"**

I notioced issue exist in 2 place , 
1)while accessing  login page URL. http://localhost:9001
2)while switching inside the bucket http://localhost:9001/browser/bk1

**Comment by balaKarur** [comment]
Hello @cesnietor @adriangitvitz
Could you please check for a refresh issue on the Windows version?

**Comment by adriangitvitz** [comment]
using this configuration with docker works, could you provide your keycloak configuration ? and also are the containers reachable ?

```
version: "3.8"
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-21T23-13-43Z
    container_name: minio
    volumes:
      - ./minio_data:/data
    command: server /data --console-address=":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Pa55w0rd
      - MINIO_SERVER_URL=http://localhost:9000/
      - MINIO_DOMAIN=http://localhost:9000/
      - MINIO_IDENTITY_OPENID_CONFIG_URL_KEYCLOAK_PRIMARY=http://host.docker.internal:8080/realms/consoletest/.well-known/openid-configuration
      - MINIO_IDENTITY_OPENID_CLIENT_ID_KEYCLOAK_PRIMARY=minio
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET_KEYCLOAK_PRIMARY=6FJmGUdCBbhiDUJCLTZ8zKzqIh6YOC4X
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME_KEYCLOAK_PRIMARY=MinIO OpenID Login
      - MINIO_IDENTITY_OPENID_CLAIM_NAME=policy
      - MINIO_IDENTITY_OPENID_VENDOR=keycloak
      - MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC_KEYCLOAK_PRIMARY=on
      - MINIO_IDENTITY_OPENID_SCOPES=minio-authorization
      - MINIO_IDENTITY_OPENID_KEYCLOAK_REALM=consoletest
      - MINIO_IDENTITY_OPENID_KEYCLOAK_ADMIN_URL=http://host.docker.internal:8080/admin
```
