### ISSUE TITLE
Prometheus unreachable on docker network

### ISSUE THREAD

**Issue by kevinmatthe** [minio/console#3347]
## NOTE
If this case is urgent, please subscribe to [SUBNET](https://min.io/pricing) so that our 24/7 support team may help you faster.

When deploying minio with docker compose, configure prometheus will always display "Prometheus unreachable"

## Expected Behavior
Show prometheus metrics on monitoring panel.

## Current Behavior
Showing "Prometheus unreachable"
![image](https://github.com/minio/console/assets/36391318/7b8ab84a-06f7-4de9-9697-0495c02b99c9)

## Possible Solution
Currently no solution found.

## Steps to Reproduce (for bugs)

Notice: the prometheus job_name == 'minio-job'
Start both service, and the error show up.

Try attaching to the minio container, use curl:
```shell
curl http://prom:9090/-/healthy
```
![image](https://github.com/minio/console/assets/36391318/28adba2d-55ce-4f10-86f8-7c122c27035e)

It works fine and prove that the network is definitely REACHABLE.

## Your Environment
Here's my example docker-compose.yaml:
**minio**:
```yaml
services:
  minio:
    command: 'server /data --console-address ":9001"'
    image: minio/minio
    restart: always
    environment:
      - MINIO_ROOT_PASSWORD=Heyuheng1.22.3
      - MINIO_ROOT_USER=kevinmatt
      - MINIO_API_CORS_ALLOW_ORIGIN=*
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_PROMETHEUS_URL="http://prom:9090"
      - MINIO_PROMETHEUS_JOB_ID=minio-job
      - MINIO_LOG_LEVEL=debug
    volumes:
      - '/mnt/StorageMirror/Storage/minio/data:/data'
    container_name: minio
    ports:
      - 29001:9001
      - 29000:9000
    expose:
      - 9001
      - 9000

networks:
  default:
    external: true
    name: homelab
```

**prometheus**:
```yaml
version: '3.7'
services:
  prometheus:
    image: prom/prometheus:main
    container_name: prom
    restart: always
    user: root:root
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention.time=1y"
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/config:/etc/prometheus
    ports:
      - 9090:9090
networks:
  default:
    external: true
    name: homelab

```

* MinIO version used (`minio --version`): RELEASE.2024-05-10T01-41-38Z
* Server setup and configuration: as the compose file defined
* Operating System and version (`uname -a`): Linux truenas 6.6.20-production+truenas #1 SMP PREEMPT_DYNAMIC Tue Apr 23 01:22:22 UTC 2024 x86_64 GNU/Linux
