### ISSUE TITLE
Console under subpath (traefik)

### ISSUE THREAD

**Issue by ahuarte47** [minio/console#3420]
I'm trying to use TRAEFIK as a reverse proxy for Minio console (Tenant) adding the subpath "miniodef". 

This is my manifest to define the ingress resource:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-tenant-miniodef-server-ingressroute
  namespace: minio-tenant-miniodef
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/protocol: https # Traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/miniodef/`)
      priority: 10
      services:
        - name: miniodef-console
          port: 9443
  tls: {}
``` 

## Expected Behavior

https://localhost:9121/miniodef/ should show the console UI

## Current Behavior

https://localhost:9121/miniodef/ shows blank page because of urls of console files do not have the subpath:
![image](https://github.com/user-attachments/assets/a490c6b6-9172-4a0f-87a0-993d14526ca6)

for example:
  https://localhost:9121/styles/root-styles.css
should be:
  https://localhost:9121/miniodef/styles/root-styles.css

## Possible Solution

Should I set `MINIO_SERVER_URL`, `MINIO_BROWSER_REDIRECT_URL` or `OPERATOR_SUBPATH` environment variables in the custom tenant values.yaml.

## Your Environment
* MinIO version used (`minio --version`): 6.0.1 Operator + Tenant
* Server setup and configuration: MinIO Operator + Tenant using Helm 6.0.1 in minikube
* Operating System and version (`uname -a`):  Ubuntu Linux 20.04

**Comment by cesnietor** [comment]
You need to specify [MINIO_BROWSER_REDIRECT_URL](https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#envvar.MINIO_BROWSER_REDIRECT_URL)  as defined in the docs?

**Comment by ahuarte47** [comment]
Hi, this is my custom values.yml for deployinh the MinIO tenant:

```
# -- Set the credentials,
# WARNING: '.secrets' is deprecated since v6.0.1 and will be removed in next minor release (i.e. v5.1.0).
# WARNING: Please use '.tenant.configSecret' instead.
#
secrets:
  name: miniodev-env-configuration
  accessKey: minio
  secretKey: minio123

# Root key for MinIO Tenant Chart
tenant:
  # -- The Tenant name,
  # Change this to match your preferred MinIO Tenant name.
  name: miniodef

  # -- The Kubernetes secret name that contains MinIO environment variable configurations.
  # The secret is expected to have a key named config.env containing environment variables exports.
  configuration:
    name: miniodev-env-configuration

  pools:
    # -- The number of MinIO Tenant Pods / Servers in this pool.
    # For standalone mode, supply 1. For distributed mode, supply 4 or more.
    # Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 1
      # Custom name for the pool.
      name: pool-0
      # The number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 1
      # The capacity per volume requested per MinIO Tenant Pod.
      size: 5Gi
      # The storageClass to associate with volumes generated for this pool.
      # If using...
      # + DirectPV CSI driver
      #   Docs: https://github.com/minio/directpv
      # + Amazon Elastic Block Store (EBS) CSI driver
      #   Docs: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md
      #   Please make sure to set xfs for "csi.storage.k8s.io/fstype" parameter under StorageClass.parameters.
      #
      storageClassName: standard

  # Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: https://localhost:9121/miniodef
``` 

None changes in my issue.

**Comment by frippe75** [comment]
I tried placing minio-console behind an NGINX-ingress-controller and trying to grasp the
https://min.io/docs/minio/linux/administration/minio-console.html#id5


>Deployments behind network routing components which require static ports for routing rules may require setting a >static MinIO Console port. For example, load balancers, reverse proxies, or Kubernetes ingress may by default block or >exhibit unexpected behavior with the the dynamic redirection behavior. 

And

> [MINIO_BROWSER_REDIRECT_URL](https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#envvar.MINIO_BROWSER_REDIRECT_URL)
> 
> The externally resolvable hostname for the MinIO Console used by the configured [external identity manager](https://min.io/docs/minio/linux/administration/identity-access-management.html#minio-authentication-and-identity-management) for returning the authentication response.[MINIO_BROWSER_REDIRECT_URL](https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#envvar.MINIO_BROWSER_REDIRECT_URL)
>

**Comment by frippe75** [comment]
So I guess setting this to my DNS name
```
env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: https://minio-console.example.com
```

**Comment by ahuarte47** [comment]
I am configuring this variable in [values.yaml](https://github.com/minio/console/issues/3420#issuecomment-2274610561) (I am deploying minio using the official Helm Chart), but with none success:
```
env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: https://localhost:9121/miniodef
```

**Comment by frippe75** [comment]
Wonder if passing the "ingress" property/key during helm install would resolve this.. will have a go.

```
ingress:
  api:
    enabled: true
    ingressClassName: "nginx"
    labels: 
      app: minio-api
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: minio-api-cert-tls
        hosts:
          - minio.home.xxx.com
    host: minio.home.xxx.com
    path: /
    pathType: Prefix
  console:
    enabled: true
    ingressClassName: "nginx"
    labels: 
      app: minio-console
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: minio-console-cert-tls
        hosts:
          - minio-console.home.xxx.com
    host: minio-console.home.xxx.com
    path: /
    pathType: Prefix
```

**Comment by frippe75** [comment]
Actually adding the following annotation solved it for me...
nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  # Ensure HTTPS is used to communicate with the service

**Comment by ahuarte47** [comment]
Thanks @frippe75 for your ideas, the key is to figure out how to translate that NGINX configuration to TRAEFIK. I tried several options with none success.

I got ArgoCD & ArgoWorkflows working behind traefik. I changed their `baseHref` value to a subpath. For example, for ArgoCD:

```yaml
configs:
  params:
    # -- New base href, service is running behind reverse proxy under subpath different from default ("/")
    server.basehref: "/argocd/"
``` 

Bot I do not know if minio-console need something similar.

**Comment by Subetov** [comment]
https://github.com/minio/console/issues/3009 marked as "closed", but
unfortunately this still doesn't work for me.
We use kubernetes ingress.
Using URL without trailing slash still results in the blank page.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: minio-console-ingress
  namespace: minio
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: minio-console
            port:
              number: 9001
        path: /minio(/|$)(.*)
        pathType: Prefix
```
