### ISSUE TITLE
Authentication to MinIO Console fails with “unable to login due to network error” when deployed via Helm

### ISSUE THREAD

**Issue by louis49** [minio/console#3510]
## Expected Behavior
I expect to be able to successfully authenticate to the MinIO Console when deploying MinIO Tenant using Helm. After providing valid credentials, the login API should return a successful authentication response (e.g., a session token) and allow access to the Console UI.

## Current Behavior
When I send a POST request to the login endpoint (e.g., POST http://localhost/api/v1/login) with valid credentials (accessKey “minio” and secretKey “minio123”), I receive a 503 response with the message:
`{"message":"unable to login due to network error"}`

Even when using a configuration that sets MINIO_BROWSER_REDIRECT_URL, MINIO_SERVER_URL, MINIO_ROOT_USER, and MINIO_ROOT_PASSWORD to “http://localhost”, authentication still fails.

## Possible Solution
I have no concrete solution at this point. I have tried various configurations (including adjusting environment variables via a secret, using different Ingress settings, and ensuring that all URLs are set to “localhost”) without success. It is possible that there is an issue with how the console processes login requests or a misconfiguration in the Helm chart.

## Steps to Reproduce (for bugs)

- Install the MinIO Operator:

```
helm repo add minio-operator https://operator.min.io
helm repo update
helm upgrade --install \
  --namespace minio-operator \
  --create-namespace \
  operator minio-operator/operator
```

- Install the MinIO Tenant 
```
helm upgrade --install \
  --namespace springpass-dev-env \
  --create-namespace \
  --values ./helm-minio/minio-values.yaml \
  minio-springpass minio-operator/tenant
```

with : minio-values.yaml 
```
tenant:
  name: myminio
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-11-07T00-52-20Z
    pullPolicy: IfNotPresent
  imagePullSecret: { }
  initContainers: [ ]
  scheduler: { }
  configuration:
    name: storage-configuration
  configSecret:
    name: myminio-env-configuration
    accessKey: minio
    secretKey: minio123
  poolsMetadata:
    annotations: { }
    labels: { }
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      size: 10Gi
      storageAnnotations: { }
      storageLabels: { }
      annotations: { }
      labels: { }
      tolerations: [ ]
      nodeSelector: { }
      affinity: { }
      resources: { }
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints: [ ]
  mountPath: /export
  subPath: /data
  metrics:
    enabled: false
    port: 9000
    protocol: http
  certificate:
    externalCaCertSecret: [ ]
    externalCertSecret: [ ]
    requestAutoCert: false
    certConfig: { }
  features:
    bucketDNS: false
    domains:
      console: http://localhost
    enableSFTP: false
  buckets: [ ]
  users: [ ]
  podManagementPolicy: Parallel
  liveness: { }
  readiness: { }
  startup: { }
  lifecycle: { }
  exposeServices:
    minio: false
    console: true
  serviceAccountName: ""
  prometheusOperator: false
  logging: { }
  serviceMetadata: { }
  env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: http://localhost
    - name: MINIO_SERVER_URL
      value: http://localhost
    - name: MINIO_ROOT_USER
      value: minio
    - name: MINIO_ROOT_PASSWORD
      value: minio123
  priorityClassName: ""
  additionalVolumes: [ ]
  additionalVolumeMounts: [ ]
ingress:
  api:
    enabled: false
    ingressClassName: ""
    labels: { }
    annotations: { }
    tls: [ ]
    host: minio.local
    path: /
    pathType: Prefix
  console:
    enabled: true
    ingressClassName: ""
    labels: { }
    annotations: { }
    host: localhost
    path: /
    pathType: Prefix
```

- Deploy env vars : 
```
helm upgrade --install test ./helm-minio \
  --namespace test \
  --create-namespace \
  -f helm-minio/values-dev.yaml 
```

with secret.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenant.configuration.name }}
type: Opaque
data:
  config.env: {{ .Values.tenant.configuration.env | b64enc | quote }}
```

with values-dev.yaml  : 
```
tenant:
  configuration:
    name: storage-configuration
    env: |
      export MINIO_BROWSER_REDIRECT_URL=http://localhost
      export MINIO_SERVER_URL=http://localhost
      export MINIO_ROOT_USER=minio
      export MINIO_ROOT_PASSWORD=minio123
```

- Test the login API with: 
```
curl --request POST --url http://localhost/api/v1/login --header 'Content-Type: application/json' --header 'Accept: application/json' --data '{"accessKey":"minio","secretKey":"minio123"}'
```

The GET request to /api/v1/login returns a JSON response (e.g., login form details), but the POST returns the error {"message":"unable to login due to network error"}.

## Context
I am deploying MinIO Tenant using the MinIO Operator and Helm on a local Minikube cluster. For simplicity, I have configured all URLs as “localhost”. I do not intend to expose the MinIO API externally; only the Console should be accessible. Despite having correct environment variables and configuration, authentication fails with a network error during login, even though the GET endpoint works as expected.

## Regression
Don't know

## Your Environment
	•	MinIO Version Used: RELEASE.2024-11-07T00-52-20Z (go1.23.3 linux/arm64)
	Deployment Setup:
  	•	MinIO Tenant deployed via Helm using the MinIO Operator on a Minikube cluster.
  	•	Configuration uses environment variables injected via a Kubernetes secret (with tenant.configuration) and directly in tenant.env.
  	•	Ingress is configured for the Console only.
	Operating System: Minikube running on a local development machine (macOS/Linux).
	Additional Notes:
	•	I have attempted to set MINIO_BROWSER_REDIRECT_URL and MINIO_SERVER_URL to “http://localhost”, and the service endpoints show “localhost” in the configuration, but authentication POST requests still return a network error.
