### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by owetterau** [minio/console#578]
After fixing #573 (many thanks for the quick solution!), I am trying to login to the console presented through an Ingress.

Unfortunately, I cannot login although access key and secret key are definitely correct.

In the logs the lines I can see are:
```
2021-01-26 10:03:08.810851 I | 2021/01/26 10:03:08 error.go:44: original error: invalid Login
2021-01-26 10:03:08.811878 I | 2021/01/26 10:03:08 error.go:124: debugging error: This 'admin' API is not supported by server in 'mode-server-distributed-xl'
```

Is there any possibility to find out what exactly is going wrong (like changing the log level)? Or is it a possible result of the fix  #573 ?

My environment is:
minio operator v3.0.29
minio console master-branch (changed manually)
Vanilla Kubernetes 1.20

**Comment by Alevsk** [comment]
Hi @owetterau make sure you are not login with MinIO root credentials, and the credentials you are using have assigned an admin policy, which version of MinIO are you currently using?

**Comment by an-tex** [comment]
I have the same issue using off the shelve https://github.com/minio/operator/blob/v3.0.29/examples/tenant.yaml and minio/console:v0.5.2

**Comment by seanjhulse** [comment]
Yup! Running into basically the same issue. Deploying on Kubernetes:

```BASH
2021-01-29 21:23:05.786008 I | 2021/01/29 21:23:05 error.go:44: original error: invalid Login
2021-01-29 21:23:05.786060 I | 2021/01/29 21:23:05 error.go:124: debugging error: This 'admin' API is not supported by server in 'mode-server-xl'
```

Deploying with a basic `tenant.yaml` configuration:

```YAML
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio-tenant-1
  namespace: minio
scheduler:
  name: ""
spec:
  ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
  ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
  ## not provided. DNS name format is *.minio.default.svc.cluster.local
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []

  ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details.
  podManagementPolicy: Parallel

  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  # env:
  # - name: MINIO_BROWSER
  #   value: "off" # to turn-off browser
  # - name: MINIO_STORAGE_CLASS_STANDARD
  #   value: "EC:2"

  ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
  ## This is applied to MinIO pods only.
  ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
  # priorityClassName: high-priority

  ## Define configuration for Console (Graphical user interface for MinIO)
  ## Refer https://github.com/minio/console
  console:
    replicas: 1
    image: minio/console:v0.5.2
    consoleSecret:
      name: console-secret
    metadata:
      creationTimestamp: null
      name: minio-tenant-1
    resources: {}
  ## Secret with credentials to be used by MinIO Tenant.
  ## Refers to the secret object created above.
  credsSecret:
    name: minio-autocert-no-encryption-minio-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: false
  serviceName: minio-tenant-1-internal-service
  zones:
  - resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
        storageClassName: standard
      status: {}
    volumesPerServer: 4
  volumes:
    - name: secret-volume
      secret:
        secretName: tls-ssl-minio
        items:
        - key: public.crt
          path: public.crt
        - key: private.key
          path: private.key
        - key: public.crt
          path: CAs/public.crt
  containers:
    - name: secret-volume
      mountPath: /root/.minio/certs
status:
  availableReplicas: 0
  currentState: ""

---
## Secret to be used for MinIO Console
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
  namespace: minio
type: Opaque
data:
  ## Passphrase to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLEACCESS' | base64)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLESECRET' | base64)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
---
## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-autocert-no-encryption-minio-creds-secret
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'minio' | base64)
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'minio123' | base64)
  secretkey: bWluaW8xMjM=
```

Deployment succeeds. I can even _see_ the console login page, but I cannot access it using the credentials which I passed (omitted and replaced with the default YOURCONSOLE* credentials).
