### ISSUE TITLE
Prometheus metrics has been re-implemented to be cluster wide from single endpoint

### ISSUE THREAD

**Issue by harshavardhana** [minio/console#588]
```yaml
scrape_configs:
- job_name: minio-job
  bearer_token: <secret>
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['localhost:9000']
```

## List of metrics exposed by MinIO

MinIO server exposes the following metrics on `/minio/v2/metrics/cluster` endpoint. All of these can be accessed via Prometheus dashboard. A sample list of exposed metrics along with their definition is available in the demo server at

```sh
curl https://play.min.io/minio/v2/metrics/cluster
```
### List of metrics reported

[The list of metrics reported can be here](https://github.com/minio/minio/blob/master/docs/metrics/prometheus/list.md)

For more questions // cc @kerneltime
