### ISSUE TITLE
docker-only scenario authentification fails

### ISSUE THREAD

**Issue by flashpixx** [minio/console#648]
Hello,

I'm new with Minio and I try to get familiar with the structure, my goal is to setup a configuration for K8 with internal & external access with LDAP authentification. I try to build first a docker-compose, which is working with LDAP, Minio and Console. This my compose file (first testing):

```
version: "3.8"

volumes:
  minio_data:  
  
services:

  console:
    image: minio/console:latest
    restart: always
    command: "server"
    ports: 
      - ${EXPOSE_PORT_CONSOLE:-9090}:9090
    environment: 
      CONSOLE_PBKDF_PASSPHRASE: SECRET1
      CONSOLE_PBKDF_SALT: SECRET2
      CONSOLE_MINIO_SERVER: http://minio:7007


  minio:
    image: minio/minio:latest
    restart: always 
    volumes:
      - minio_data:/data
    ports:
      - ${EXPOSE_PORT_MINIO:-7007}:7007
    command: "minio server --address :7007 /data"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
```

I can login under http://localhost:7007 on the Minio, but on the Console http://localhost:9090 I can't login. I try to follow the steps on the readme with the mc commands, but in this case I'm using the minio/mc docker container, but in this case mc does not know the console. So my question is how can I login in the console and connect the console to my running minio container? I get on console login an "unauthorizied" error message

**Comment by dvaldivia** [comment]
for LDAP, you need to configure the MinIO server first

```
 env:
    - name: MINIO_IDENTITY_LDAP_SERVER_ADDR
      value: "openldap.address:389"
    - name: MINIO_IDENTITY_LDAP_USERNAME_FORMAT
      value: "uid=%s,dc=example,dc=org"
    - name: MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER
      value: "(|(objectclass=posixAccount)(uid=%s))"
    - name: MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY
      value: "on"
    - name: MINIO_IDENTITY_LDAP_SERVER_INSECURE
      value: "on"
```

and then let console know LDAP is enabled


```
- name: CONSOLE_LDAP_ENABLED
        value: "on"
```
