### ISSUE TITLE
Self-signed certificate IDP

### ISSUE THREAD

**Issue by Sleepy-GH** [minio/console#667]
I'm running the minio operator to deploy both minio and console on my Kubernetes cluster. I've configured console to look at my Keycloak (externally hosted with Self-signed certificate) for OpenID IDP.

I'm getting an error on the Self-signed certificate part. Is there a way to either trust this cert or to skip cert validation on this?

**Comment by Alevsk** [comment]
@Sleepy-GH yes, create a new kubernetes secret that contains the root ca certificate used to verify the self-signed certificate, then in your tenant CRD use the `externalCaCertSecret` field to pass that secret name, this field is supported for both, minio and console, ie:
```
spec:
  externalCaCertSecret:
    - name: yourCertificateSecretHere
  ...
  ...
  console:
       externalCaCertSecret:
         - name: yourCertificateSecretHere
```
