### ISSUE TITLE
TLS with docker seems not working

### ISSUE THREAD

**Issue by edwardzjl** [minio/console#682]
I'm starting minio/console from docker compoes file, and trying to mount key and crt file into the container (~/some_folder:/root/.console/certs)
It works for minio server, but for console it just has no effect.
The compose file:

```yaml
version: "3"

services: 
  minio-server:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ~/.config/minio:/root/.minio
    command: ["server", "/data"]

  minio-console:
    image: minio/console
    restart: always
    ports:
      - "9090:9090"
    environment:
      - CONSOLE_PBKDF_PASSPHRASE=SECRET
      - CONSOLE_PBKDF_SALT=SECRET
      - CONSOLE_MINIO_SERVER=https://minio-server:9000
    volumes:
      - ~/.config/minio:/root/.console
    entrypoint: ["./console", "server"]
    depends_on: 
      - minio-server 
```

The ```~/.config/minio``` folter I mount into containers contains public.crt and private.key:

![微信截图_20210402174619](https://user-images.githubusercontent.com/7287580/113404806-5948db80-93db-11eb-825c-385fa7e2e59b.png)

After the containers up I can access minio server over https, but for minio console I can only access with http, not https, with following error

![微信截图_20210402174301](https://user-images.githubusercontent.com/7287580/113404550-e93a5580-93da-11eb-921b-694d4b0afce5.png)

It seems my key and crt file was not recognized by minio console?
