### ISSUE TITLE
No data in dashboard

### ISSUE THREAD

**Issue by guemidiborhane** [minio/console#757]
We installed MinIO in our production HA k3s cluster, everything works fine except the dashboard that doesn't show any data and raises an error when trying to set range `Step in query must be of type int64`

![dashboard](https://user-images.githubusercontent.com/4106935/118882577-3f604b00-b8ec-11eb-9f20-e10bc74a7e1a.png)

**Comment by harshavardhana** [comment]
> We installed MinIO in our production HA k3s cluster, everything works fine except the dashboard that doesn't show any data and raises an error when trying to set range `Step in query must be of type int64`

@guemidiborhane please set CONSOLE_PROMETHEUS_JOB_ID if you have customized your prometheus job-id. 

Otherwise, the dashboard works fine login here https://play.min.io:9443/dashboard 

username: minio
password: minio123

**Comment by guemidiborhane** [comment]
Hello @harshavardhana,

we did not customize the prometheus job-id.

**Comment by harshavardhana** [comment]
> Hello @harshavardhana,
> 
> we did not customize the prometheus job-id.
> 
> Edit: Can you give me a bit more info about this config.

Share your Prometheus configuration?

**Comment by guemidiborhane** [comment]
> > Hello @harshavardhana,
> > we did not customize the prometheus job-id.
> > Edit: Can you give me a bit more info about this config.
> 
> Share your Prometheus configuration?

```yaml
# This file and config-map is generated by MinIO Operator.
# DO NOT EDIT.

global:
  scrape_interval: 30s
  evaluation_interval: 30s
scrape_configs:
- job_name: minio
  bearer_token: token
  metrics_path: /minio/v2/metrics/cluster
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  static_configs:
  - targets:
    - minio.object-storage.svc.cluster.local:443
```
