### ISSUE TITLE
Dashboard data not working

### ISSUE THREAD

**Issue by cbfischer** [minio/console#799]
**Dashboard NO data:**
![image](https://user-images.githubusercontent.com/34420293/121236320-323fd780-c86c-11eb-9096-2980a594e868.png)

**Info Cluster**
![image](https://user-images.githubusercontent.com/34420293/121240473-c14eee80-c870-11eb-9880-cad2c1736e8e.png)

**Console Version**
![image](https://user-images.githubusercontent.com/34420293/121238355-64523900-c86e-11eb-9200-62237fdb25d4.png)

mc version RELEASE.2021-06-08T01-29-37Z

**Prometheus**
![image](https://user-images.githubusercontent.com/34420293/121238073-150c0880-c86e-11eb-81b9-082d9455a034.png)
version:
![image](https://user-images.githubusercontent.com/34420293/121238256-4b498800-c86e-11eb-8a19-cf3b74d019d1.png)
test with curl:
![image](https://user-images.githubusercontent.com/34420293/121239364-88624a00-c86f-11eb-9e9e-d75925b57aa0.png)
targets:
![image](https://user-images.githubusercontent.com/34420293/121240125-64ebcf00-c870-11eb-997d-ae3b53d61b77.png)

**Console ENV** 
![image](https://user-images.githubusercontent.com/34420293/121236711-9ebad680-c86c-11eb-9c4f-7d10bdc792ef.png)

![image](https://user-images.githubusercontent.com/34420293/121237718-bba3d980-c86d-11eb-8d4b-51eac5062bb2.png)

**MINIO ENV**
![image](https://user-images.githubusercontent.com/34420293/121240732-0bd06b00-c871-11eb-9ed3-17297253b060.png)

**Comment by harshavardhana** [comment]
Your prometheus.yml is wrong do not know where you got that from you need to set 

```
mc admin prometheus generate play/
scrape_configs:
- job_name: minio-job
  metrics_path: /minio/v2/metrics/cluster
  scheme: https
  static_configs:
  - targets: [play.min.io]
```

NOTE: the `metrics_path` should be correct.
